<?php
/**
 * WaPoNe
 *
 * @category   WaPoNe
 * @package    WaPoNe_Stickers
 * @copyright  Copyright (c) 2017 WaPoNe (http://www.fantetti.net)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

if($block->isDiscountActive()):
    $discountImage = "<div class='wapone-sticker-wrapper top-right'>";
    $discountImage .= "<img class='categoryDiscountImage' alt='".__('Discount')."' src='".$this->getUrl('pub/media')."wapone/stickers/images/".$block->getStickerImage()."' />";
    $discountImage .= "</div>";
    $discountArea = "<div class='wapone-sticker-wrapper top-right'>";
    $discountArea .= "<div class='wapone-sticker discount-product";
    if ($block->isAutomaticMode()) $discountArea .= " automatic";
    $discountArea .= "' style='background-color: #".$block->getStickerBackground()."; color: #".$block->getStickerText().";'></div>";
    $discountArea .= "</div>";
?>

<script type="text/x-magento-init">
    {
        "*":{
            "categoryPageDiscount":{
                "imageTag": {
                  "discountImage": "<?php /* @escapeNotVerified */  echo $discountImage; ?>",
                  "discountArea": "<?php /* @escapeNotVerified */  echo $discountArea; ?>"
                }
            }
        }
    }
</script>

<?php
    endif;
