<?php
/**
 * WaPoNe
 *
 * @category   WaPoNe
 * @package    WaPoNe_Stickers
 * @copyright  Copyright (c) 2017 WaPoNe (http://www.fantetti.net)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

if($block->isDiscountActive()):
    $productDiscountBlock = $block->setDiscountStickerHTML();
    ?>

<script type="text/x-magento-init">
    {
        "*":{
            "viewPageDiscount":{
                "imageTag": {
                  "imagePath": "<?php /* @escapeNotVerified */  echo $productDiscountBlock; ?>"
                }
            }
        }
    }
</script>

<?php
    endif;
